### ISSUE TITLE
CPU Limitation

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#1021]
Tell me if it is possible to limit the CPU usage in the docker compass, so that there are few resources left for other applications.
I found an opportunity to add a record to the service

```
version: '3'
services:
  myservice:
    image: myimage
    cpus: 0.8
```

In this example, we limit the myservice container's usage to no more than 80% of the host machine's CPU time using the cpus option. The value 0.8 means that the container will have access to 80% of the processor's core time.

or

```
version: '3'
services:
  myservice:
    image: myimage
    cpuset: "0-2"
```

In this example, the myservice container will be limited to using CPU cores 0 to 2.

cpuset is a parameter that allows you to explicitly set on which CPU cores or CPU core groups a container will run. This is useful when you want to control which processor cores are used for different containers.

But with such a limitation, the backend crashes with an error 

```
backend         | [2023-09-18 13:22:47 +0000] [113] [INFO] Worker exiting (pid: 113)
backend         | [2023-09-18 13:22:48 +0000] [80] [ERROR] Worker (pid:113) was sent SIGKILL! Perhaps out of memory?

```

Docker Compose also supports other options for limiting CPU time:

1. `cpu_shares`: This option allows you to set the relative priority of CPU time usage for containers. The higher the `cpu_shares` value, the higher priority the container gets in CPU time allocation. By default, all containers have the same `cpu_shares` value. Example:

   ```
   version: '3'
   services:
     myservice:
       image: myimage
       cpu_shares: 512
   ```

2. `cpu_quota` and `cpu_period`: With these options, you can explicitly set a quota (amount of CPU time) and period (duration of time period) for the container. The quota is specified in microseconds of CPU time per period, which is also specified in microseconds. Example:

   ```
   version: '3'
   services:
     myservice:
       image: myimage
       cpu_quota: 50000
       cpu_period: 100000
   ```

   In this example, the `myservice` container is allowed to use no more than half of the host machine's CPU time.

Note that using these options in Docker Compose requires support from your host system and Docker Compose version 3.2 or above. Consult the Docker documentation for more detailed information and clarifications regarding the availability of these options in your Docker runtime environment.

The last two options do not seem to have given a visual result.

Maybe someone was interested in this question
