### ISSUE TITLE
Proxy won't start due to port 3000 already in use

### ISSUE THREAD

**Issue by mcwieger** [LibrePhotos/librephotos#315]
I'm trying to start librephotos in Docker on a Synology, but running into an error when starting the proxy container.

I use Docker Compose, with the following ports:

```
  proxy:
    image: guysoft/ownphotos-proxy
    tty: true
    container_name: ownphotos-proxy
    restart: always
    links:
      - "backend:backend"
      - "frontend:frontend"
    ports:
      - "3000:80"
```
and
`       - BACKEND_HOST=localhost:3001 # CHANGE ME IF YOU WANT`

As you can see, I changed the port of the backend host to 3001 already, as 3000 is in use by a different application (ZwaveJS2MQTT, which is integrated with Home Assistant. I don't want to mess up that integration, so rather won't change that port).

In the first section of docker-compose.yml, port 3000 is also mentioned, but it doesn't say I can change it. I did to try if it would fix the issue and the proxy starts, but I can't connect to localhost:3001 after that, so it doesn't fix the issue as a whole.

Error message I get:
`ERROR: for ownphotos-proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint ownphotos-proxy (a112f0d6dd845e33c0dd75b14e03ee7b81f3ad0f69141631e7fe5d9a483a1d73): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use`

Is there a way I can use a different port than 3000 or a way I can bypass it (host mode, perhaps. If so, how)?
