### ISSUE TITLE
Option to set scan directory missing in admin area

### ISSUE THREAD

**Issue by 92Magnum** [LibrePhotos/librephotos#51]
Followed the recommended Docker-compose method.
I have modified only the path to volumes under the backend inside the docker-compose.yml file (as shown)

```
  backend:
    image: reallibrephotos/librephotos:dev
    # For development uncomment the "build" line below and comment the "image" line above
    # build: .
    container_name: librephotos-backend
    restart: always
    volumes:
      - $HOME/Pictures/librephotos/librephotos_images:/data # CHANGE ME
      - $HOME/Pictures/librephotos/librephotos_media:/code/protected_media # CHANGE ME
      - $HOME/Pictures/librephotos/librephotos_logs:/code/logs # CHANGE ME
      - $HOME/Pictures/librephotos/librephotos_cache:/root/.cache # CHANGE ME
```

Logged in as admin but the link to set the scan directory is missing. 
![librephotos_no_directory](https://user-images.githubusercontent.com/41338195/103230247-f61e5780-495a-11eb-96e5-8ba07c94373f.png)

Not sure if this helps but found this issue in the backend logs on running **docker logs librephotos-backend**

Traceback (most recent call last):
  File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/miniconda/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/miniconda/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/miniconda/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/miniconda/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 91, in technical_500_response
    text = reporter.get_traceback_text()
  File "/miniconda/lib/python3.8/site-packages/django/views/debug.py", line 341, in get_traceback_text
    return t.render(c)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "/miniconda/lib/python3.8/site-packages/django/template/base.py", line 693, in resolve
    obj = template_localtime(obj, context.use_tz)
  File "/miniconda/lib/python3.8/site-packages/django/utils/timezone.py", line 186, in template_localtime
    return localtime(value) if should_convert else value
  File "/miniconda/lib/python3.8/site-packages/django/utils/timezone.py", line 204, in localtime
    timezone = get_current_timezone()
  File "/miniconda/lib/python3.8/site-packages/django/utils/timezone.py", line 97, in get_current_timezone
    return getattr(_active, "value", get_default_timezone())
  File "/miniconda/lib/python3.8/site-packages/django/utils/timezone.py", line 83, in get_default_timezone
    return pytz.timezone(settings.TIME_ZONE)
  File "/miniconda/lib/python3.8/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
`
