### ISSUE TITLE
More specific Hostname

### ISSUE THREAD

**Issue by M4RC02U1F4A4** [LibrePhotos/librephotos#61]
I noticed that the backend and the frontend are called from other container with the name `backend` and `frontend`

Example: https://github.com/LibrePhotos/librephotos-proxy/blob/582783abbac3a59df4e85b5a641e768fea1c9493/nginx.conf#L19

I need to run each container present in the docker-compose manually (i can't user docker-compose) and that name scheme can create problem
It also can be a problem if these container are inserted in the same network with other Docker container

In my opinion it would be better to change the names to be more specific, like `frontend` with `librephotos-frontend`

I saw that this convention came out already for the container name, but I think it would be better to extend it to all the code

**Comment by anatosun** [comment]
This can be done with docker-compose links (https://docs.docker.com/compose/networking/#links) like the following, provided you have changed the frontend and backend service's name accordingly.
```
librephotos-proxy:
    image: reallibrephotos/librephotos-proxy:${tag}
    links:
      - "librephotos-backend:backend"
      - "librephotos-frontend:frontend"
    tty: true
    container_name: librephotos-proxy
    restart: always
    ports:
      - 3000:80
```
