### ISSUE TITLE
My Albums disappear and new ones are no longer created/visible : Showing 0 user created albums

### ISSUE THREAD

**Issue by Circenn5130** [LibrePhotos/librephotos#664]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files [gunicorn_django.log](https://github.com/LibrePhotos/librephotos/files/9791059/gunicorn_django.log)
* [X] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue [Example of behavior](https://gfycat.com/officialadoredbufflehead)

## 📝 Description of issue:
After uploading photos then adding them into an album, any albums previously created disappear. Attempts to recreate previous albums or create new ones still results in **Showing 0 user created albums**
All pictures are still present
Albums shared with a second account are still visible for the second account
Sometimes I'm able to setup 4 or 5 new albums, but every time at some point it will no longer show any albums

I'm not sure what logs are necessary to help 

### [Following Docker install steps](https://docs.librephotos.com/1/standard_install/)
`cd librephotos-docker`
`cp librephotos.env .env`

### Edit .env the following variables
```
scanDirectory=~/scanDirectory
data=./librephotos/data
logs=~/logs
dbName=librephotos
dbUser=librephotos
dbPass=<pass>
```
### From docker-compose.yml

```
  backend:
    image: reallibrephotos/librephotos:${tag}
    container_name: backend
    restart: unless-stopped
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
      - ${logs}:/logs
      - ${data}/cache:/root/.cache
```
### docker-compose up

- Begin uploading photos from localhost:3000
- Wait until worker is green and available (upper right)
- Select uploaded photos and click the + to add to an album
- Go to Albums > My albums > refresh page to see new data  

## Please provide additional information:
- 💻 Operating system: 
Debian 11 Bullseye (Standard), from Proxmox templates

- ⚙ Architecture (x86 or ARM): 
 x86_64

- 🔢 Librephotos version: 
 reallibrephotos/librephotos-frontend   latest 
 reallibrephotos/librephotos            latest 
 reallibrephotos/librephotos-proxy

- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): 
 Docker : latest
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): 
 Cephfs with a symlink  from cephfs to workingdir \librephotos-docker

 scanDirectory -> /mnt/pictures/librephotos/scanDirectory/

- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): 
 Proxmox VE 7.2
