### ISSUE TITLE
ARM64/PyTorch Fatal Python error: Illegal instruction

### ISSUE THREAD

**Issue by Mindstan** [LibrePhotos/librephotos#744]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files: [podman_logs.zip](https://github.com/LibrePhotos/librephotos/files/10611396/logs.zip)
* [X] ❌ I have looked for similar issues (including closed ones)

## 📝 Description of issue:

When starting a scan from Nextcloud, the workers are crashing with the error `Fatal Python error: Illegal instruction`, which is coming from PyTorch.

The backend is deployed using the `docker-compose.yml` and Podman (4.3), on a Raspberry Pi 4 8Go v1.

This is a duplicate of https://github.com/LibrePhotos/librephotos/issues/406, but the bug is still present in both `latest` and `dev` Docker images. It was working back in November 2022, but I couldn't make it work since.

It looks like every other functionalities (that does not involve scanning new images) are working as they usually do.

## 🔁 How can we reproduce it:

Start a scan on an ARM64 device running in Docker/Podman.

## Please provide additional information:
- 💻 Operating system: Raspberry Pi OS 64bits (Debian 11, up to date), kernel `5.15.84-v8+`.

- ⚙ Architecture (x86 or ARM): ARM64 (armv8)
- 🔢 Librephotos version: 2023-01-30T11:15:53.089771527Z
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernetes, provide docker-compose image tag: both `latest` and `dev`
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): Local filesystem as Docker volume

Bellow is the slightly modified `docker-compose.yml` I’m using :
```yaml
version: "3.8"

networks:
  proxy:
    external: true

services:
  proxy:
    image: docker://reallibrephotos/librephotos-proxy:${tag}
    container_name: librephotos-proxy
    restart: always
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
    ports: # - ${httpPort}:80
    depends_on:
      - backend
      - frontend
    networks:
      - proxy
    labels:
      traefik.http.routers.photos.entrypoints: websecure
      traefik.http.routers.photos.rule: Host(`photos.domain`)
      traefik.http.services.photos.loadbalancer.server.port: 80
      traefik.enable: true

  db:
    image: docker://postgres:13
    container_name: librephotos-db
    restart: always
    environment:
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPass}
      - POSTGRES_DB=${dbName}
    volumes:
      - ${data}/db:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    #Checking health of Postgres db
    healthcheck:
      test: psql -U ${dbUser} -d ${dbName} -c "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: docker://reallibrephotos/librephotos-frontend:${tag}
    container_name: librephotos-frontend
    restart: always
    depends_on:
      - backend

  backend:
    image: docker://reallibrephotos/librephotos:${tag}
    container_name: librephotos-backend
    restart: always
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
      - ${data}/logs:/logs
      - ${data}/cache:/root/.cache

    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=${dbHost}
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${mapApiKey}
      - WEB_CONCURRENCY=${gunniWorkers}
      - SKIP_PATTERNS=${skipPatterns}
      - ALLOW_UPLOAD=${allowUpload}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS}

    # Wait for Postgres
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: docker://redis:6
    container_name: librephotos-redis
    restart: always
```
