### ISSUE TITLE
Are there limitations on filesystems for photo hosting? 

### ISSUE THREAD

**Issue by rafntor** [LibrePhotos/librephotos#97]
Mine are on NTFS and when running librephotos under docker-desktop with ubuntu / wsl 2 engine and pointing "/data" to the wsl-windows-mount it does not seem to get picked up. When I go to admin area and try to assign user directory there is no directory listed to choose from

config snippet ;
``` yaml
backend:
    image: reallibrephotos/librephotos:dev
    volumes:
      - /mnt/g/auto-backedup/camera/:/data:ro
```
 
![image](https://user-images.githubusercontent.com/44544090/103487512-5a7f6200-4e06-11eb-8140-f600d862128b.png)
